version: '3.8'

services:
  waha:
    image: devlikeapro/whatsapp-http-api
    ports:
      - "3000:3000"
    volumes:
      - ./waha-data:/app/tokens

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - WAHA_URL=http://waha:3000
    depends_on:
      - waha 